spring:
  application:
    name: springbootdemo
  datasource:
    url: jdbc:mysql://localhost:3306/demo
    username: app
    password: app

  sql:
    init:
      mode: always

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    
server:
  port: 2222